### ISSUE TITLE
Complete the License Update to MIT and Apache v2

### ISSUE THREAD

**Issue by levinem** [racket/racket2-rfcs#115]
If part of the goal is to increase Racket usage and its target audience, I think it would be beneficial to complete the already initiated relicensing of Racket under the MIT and Apache V2 licenses being tracked in [this Racket issue](https://github.com/racket/racket/issues/1570).  A more business-friendly, permissive license can also do a lot to make a particular language more acceptable and justifiable in commercial, production applications.

**Comment by spdegabrielle** [comment]
Hi @levinem

I'm not part of the racket team, so my response is based on following #1570 and folling the racket-users list.

My understanding is that #1570 is still in progress. 

You can subscribe to #1570 notifications to track the progress of the issue.

If you are happy with this response would you consider closing this issue as a duplicate of  #1570 ?

If you are interested in supporting Racket please take a look at the opportunities listed at https://github.com/racket/racket/wiki/Support-Racket 

Kind regards

Stephen

**Comment by levinem** [comment]
:) No problem, I will close this issue and will continue to subscribe to #1570.  Thanks for reaching out!
