### ISSUE TITLE
Change `match` to recognize clauses based on bindings instead of symbols, and make   it treat `else` like `cond`.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket2-rfcs#40]
Change `match` to recognize clauses based on bindings instead of symbols, and make
  it treat `else` like `cond`.

from Wishlist of backwards incompatible things for a future Racket2. #33

**Comment by sorawee** [comment]
I think this is already in #23.

**Comment by spdegabrielle** [comment]
Closed as duplicate of #23
